name: Build
on: 
  workflow_dispatch:
  push:
    tags:
      - '**'
    branches:
      - "**"

env:
  IMAGE_NAME: ${{ github.repository_owner }}/restic-backupclient

jobs:
  test-postgres17:
    name: Postgres17 Integrationtest
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Run Postgres17 Test
        run: |
          chmod +x test/test_postgres.sh
          test/test_postgres.sh

  build:
    name: build and push
    runs-on: ubuntu-latest
    needs: 
      - test-postgres17
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: wustus
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
